version: "3.9"

services:

  web:
    image: nginx:1.18.0
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/hillel.loc/


  php:
    build: ./docker/php
    ports:
    - "9000:9000"
    volumes:
    - ./:/var/www/hillel.loc


  mysql:
    image: mysql:8.0.23

    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    env_file:
      - .env
